### ISSUE TITLE
Locatie aangeven op de kaart bij het registreren van een device.

### ISSUE THREAD

**Issue by SavaSharif** [hro-sma/weather-station-server#32]
Op dit moment moet je zelf je locatie invullen. Dit is niet erg handig, aangezien je dan verschillende varianten krijgt van een plaats, en omdat het niet specifiek is.

Door een kaart op de pagina te plaatsen hebben we ook gelijk een visuele representatie van alle opgestuurde data.

Verder is het ook handig als de pointer automatisch op de locatie van de gebruiker wordt neergezet bij het laden van de pagina.

**Comment by Trottero** [comment]
Fixed in #36
