### ISSUE TITLE
Ratelimiting voor requests is niet endpoint specifiek.

### ISSUE THREAD

**Issue by Trottero** [hro-sma/weather-station-server#44]
## Samenvatting
Op dit moment staan er boven de endpoints bepaalde limiten. Deze limieten voelen een beetje inconsistent. 

## Stappen om het probleem te reproduceren
1. Stuur een request om een update aan te maken. Dit zorgt ervoor dat je 5 minuten als het goed is geen request meer aan kan maken

2. Probeer een get latest request uit te voeren. Dit request zal, ook al heeft deze endpoint maar een limit van 10 seconden, worden geweigerd doordat er al een request is gedaan naar de webserver. Je moet dus 5 minuten wachten om een latest op te halen nadat je hebt gepost.

## Verwachte resultaat
Verwachtte resultaat is dat deze endpoints apart bijhouden welke requests er naartoe zijn gestuurd. Hierdoor voelt de API een stuk gemakkelijker om te gaan gebruiken.

## Extra informatie
@n9iels pls fix.

**Comment by n9iels** [comment]
fixed in #45
